server:
  port: 8762

spring:
  profiles:
    active: peer2

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer1:8762/eureka/

